cluster_name: rke2-mgmt
system_default_registry: ""

rke2_version: v1.29.6+rke2r1

vm:
  image: ubuntu
  qemu_agent_install: true          
  qemu_agent_enable: true           
  airgapped_image: false  

registry_config:
  configs:
    "rgcrprod.azurecr.us":
      auth:
        username: test
        password: test

control_plane:
  vip: 10.10.0.35 
  loadbalancer_gateway: 10.10.0.1
  loadbalancer_subnet: 10.10.0.0/24
  
  node_count: 3 
  cpu_count: 8
  memory_gb: 16

  ipam: static
  network:
  - |
    network:
      version: 2
      renderer: networkd
      ethernets:
        enp1s0:
          dhcp4: no
          addresses: [ "10.10.0.36/24" ]
          gateway4: 10.10.0.1
          nameservers:
            addresses: 
            - 10.10.0.1
  - |
    network:
      version: 2
      renderer: networkd
      ethernets:
        enp1s0:
          dhcp4: no
          addresses: [ "10.10.0.37/24" ]
          gateway4: 10.10.0.1
          nameservers:
            addresses: 
            - 10.10.0.1
  - |
    network:
      version: 2
      renderer: networkd
      ethernets:
        enp1s0:
          dhcp4: no
          addresses: [ "10.10.0.38/24" ]
          gateway4: 10.10.0.1
          nameservers:
            addresses: 
            - 10.10.0.1
  
worker:
  node_count: 0