apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    network.harvesterhci.io/clusternetwork: mgmt
    network.harvesterhci.io/ready: 'true'
    network.harvesterhci.io/type: UntaggedNetwork
  name: host
  namespace: default
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"host","type":"bridge","bridge":"mgmt-br","promiscMode":true,"ipam":{}}