apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  name: ${CLUSTER_NAME}-lb-pool
spec:
  ranges:
    - gateway: ${LOAD_BALANCER_GATEWAY}
      rangeEnd: ${LOAD_BALANCER_IP}
      rangeStart: ${LOAD_BALANCER_IP}
      subnet: ${LOAD_BALANCER_CIDR}
  selector: {}